### PR TITLE
Section 2,3,4 and MQ

### PR DESCRIPTION
**Pull request by LiluUncharted**
I tried to make a video block by uploading mp4. In the mobile version, it didn’t work out to align and I just set value display:none. I also added JS for the play button. I'm not sure if it's right, but I tried))

Web capture_4-9-2023_0385_
Web capture_4-9-2023_03715_

### CODE REVIEW

**Review by Irrreny — APPROVED** [review]
Looks great, nothing to add from my side :)

**Comment by ElenaF95** [comment]
Very good, full size looks like a figma layout, I like it.

**Review by ElenaF95 — APPROVED** [review]

**Comment by LiluUncharted** [comment]
> Looks great, nothing to add from my side :)

Thank you))

**Comment by LiluUncharted** [comment]
> Very good, full size looks like a figma layout, I like it.

Thanks)))

**Review by IvanCeban — APPROVED** [review]
Just perfect!
Good for using JS!

**Pull request merged**
